name: Build and Publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Publish head Docker image
        uses: VaultVulp/gp-docker-action@1.1.6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          image-name: eat-out-server
          image-tag: latest
